"""Generate deterministic local-coach fixtures from KanjiVG templates.

The output is intentionally small and contains only the five Phase 1 acceptance
characters. Run from the repository root:

    python scripts/generate_realtime_fixtures.py
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path
import sys

import numpy as np

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from scorer.kanjivg import load_char


TARGET_CHARACTERS = ("永", "水", "木", "日", "語")


def _round_strokes(strokes: list[np.ndarray]) -> list[list[list[float]]]:
    return [np.round(stroke, 6).tolist() for stroke in strokes]


def _copy(strokes: list[np.ndarray]) -> list[np.ndarray]:
    return [stroke.copy() for stroke in strokes]


def _start_offset(strokes: list[np.ndarray]) -> list[np.ndarray]:
    out = _copy(strokes)
    weights = np.linspace(1.0, 0.0, len(out[0]))[:, None]
    out[0] = np.clip(out[0] + weights * np.asarray([0.12, -0.02]), 0.0, 1.0)
    return out


def _end_offset(strokes: list[np.ndarray]) -> list[np.ndarray]:
    out = _copy(strokes)
    weights = np.linspace(0.0, 1.0, len(out[0]))[:, None]
    out[0] = np.clip(out[0] + weights * np.asarray([-0.02, 0.12]), 0.0, 1.0)
    return out


def _path_deviation(strokes: list[np.ndarray]) -> list[np.ndarray]:
    out = _copy(strokes)
    stroke = out[0]
    direction = stroke[-1] - stroke[0]
    normal = np.asarray([-direction[1], direction[0]], dtype=np.float64)
    norm = float(np.linalg.norm(normal))
    if norm < 1e-9:
        normal = np.asarray([0.0, 1.0])
    else:
        normal /= norm
    bump = np.sin(np.linspace(0.0, np.pi, len(stroke)))[:, None] * 0.13
    out[0] = np.clip(stroke + bump * normal, 0.0, 1.0)
    return out


def _reversed(strokes: list[np.ndarray]) -> list[np.ndarray]:
    out = _copy(strokes)
    out[0] = out[0][::-1].copy()
    return out


def _shortened(strokes: list[np.ndarray]) -> list[np.ndarray]:
    out = _copy(strokes)
    stroke = out[0]
    out[0] = stroke[0] + (stroke - stroke[0]) * 0.55
    return out


def _lengthened(strokes: list[np.ndarray]) -> list[np.ndarray]:
    out = _copy(strokes)
    stroke = out[0]
    out[0] = np.clip(stroke[0] + (stroke - stroke[0]) * 1.45, 0.0, 1.0)
    return out


def build_fixtures(kanji_dir: Path) -> dict:
    characters = {}
    for char in TARGET_CHARACTERS:
        template = load_char(str(kanji_dir), char)
        characters[char] = {
            "template": _round_strokes(template),
            "cases": {
                "perfect": _round_strokes(template),
                "start_offset": _round_strokes(_start_offset(template)[:1]),
                "end_offset": _round_strokes(_end_offset(template)[:1]),
                "path_deviation": _round_strokes(_path_deviation(template)[:1]),
                "direction_reversed": _round_strokes(_reversed(template)[:1]),
                "too_short": _round_strokes(_shortened(template)[:1]),
                "too_long": _round_strokes(_lengthened(template)[:1]),
            },
        }
    return {
        "protocol_version": 1,
        "source": "KanjiVG templates normalized by scorer.kanjivg.load_char",
        "characters": characters,
    }


def _module_text(fixtures: dict) -> str:
    templates = {
        char: data["template"]
        for char, data in fixtures["characters"].items()
    }
    encoded = json.dumps(templates, ensure_ascii=False, separators=(",", ":"))
    return (
        "// Generated by scripts/generate_realtime_fixtures.py.\n"
        f"export const BUILTIN_TEMPLATES = Object.freeze({encoded});\n\n"
        "export function getBuiltinTemplate(char) {\n"
        "  const template = BUILTIN_TEMPLATES[char];\n"
        "  return template\n"
        "    ? template.map((stroke) => stroke.map((point) => [...point]))\n"
        "    : null;\n"
        "}\n"
    )


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--kanji-dir", type=Path, default=ROOT / "kanji")
    parser.add_argument(
        "--json-output",
        type=Path,
        default=ROOT / "tests" / "fixtures" / "realtime-strokes.json",
    )
    parser.add_argument(
        "--module-output",
        type=Path,
        default=ROOT / "web" / "coach" / "builtin-templates.js",
    )
    args = parser.parse_args()

    fixtures = build_fixtures(args.kanji_dir)
    args.json_output.parent.mkdir(parents=True, exist_ok=True)
    args.module_output.parent.mkdir(parents=True, exist_ok=True)
    args.json_output.write_text(
        json.dumps(fixtures, ensure_ascii=False, indent=2) + "\n",
        encoding="utf-8",
    )
    args.module_output.write_text(_module_text(fixtures), encoding="utf-8")
    print(f"wrote {args.json_output}")
    print(f"wrote {args.module_output}")


if __name__ == "__main__":
    main()
