create table if not exists public.writing_attempts (
  id bigint generated by default as identity primary key,
  protocol_version smallint not null check (protocol_version = 1),
  session_id text not null check (char_length(session_id) between 1 and 128),
  attempt_id text not null check (char_length(attempt_id) between 1 and 128),
  attempt_revision integer not null check (attempt_revision >= 0),
  chr text not null check (char_length(chr) >= 1),
  mode text not null check (mode in ('trace', 'recall')),
  ended_reason text not null check (
    ended_reason in ('scored', 'score_failed', 'cleared', 'character_changed', 'page_hidden')
  ),
  started_at timestamptz not null,
  ended_at timestamptz not null,
  strokes jsonb not null,
  stroke_results jsonb not null,
  final_score double precision check (final_score between 0 and 100),
  training_consent boolean not null default false check (training_consent = false),
  client_version text not null check (char_length(client_version) between 1 and 64),
  created_at timestamptz not null default now(),
  unique (attempt_id, attempt_revision)
);

alter table public.writing_attempts enable row level security;
revoke all on table public.writing_attempts from anon, authenticated;

comment on table public.writing_attempts is
  'Anonymous end-of-attempt batches. Raw point order and optional pen metadata are retained for consent-gated model improvement.';
